### ISSUE TITLE
如何让一个 div 元素宽高比保持一定？

### ISSUE THREAD

**Issue by lijunlin2022** [lijunlin2022/blog#3]
可以使用 css 里的元素 `aspect-ratio`，它可以直接指定宽高比：

```css
div {
  /* 宽高比为 4 : 1 */
  aspect-ratio: 4/1;
}
```
